### ISSUE TITLE
The pre-trained models are not found

### ISSUE THREAD

**Issue by amandazw** [Amazingren/CIT#3]

**Comment by Amazingren** [comment]
Hi @amandazw ,
Thank you for your interest in our work，we will provide them later (Since I changed the sever recently, I will upload it once I get everything done). But you can train it by yourself if you are in a hurry(It may cost you a total of 2~3 days to train both stages on one V100 GPU).

**Comment by amandazw** [comment]
THX!
I'll try it and take your time~

**Comment by amandazw** [comment]
Hi @Amazingren,
I'm here to return the result.
![000010_0](https://user-images.githubusercontent.com/20120287/120579610-66755b80-c45a-11eb-826c-4156028e57fc.jpg)
 The GMM step is good, but after I finished the TOM step,I run the test of TOM:
![000010_0](https://user-images.githubusercontent.com/20120287/120579931-e26fa380-c45a-11eb-8960-223fdde66b3f.jpg)
I use pytorch 1.1.0, torchvision 0.3.0 to train GMM, using torch 1.8.1+cu111,torchvision  0.9.1+cu111 to train TOM as when I train the TOM model,it showed CUDA out of memory,so I changed to another higher performance GPU.

**Comment by amandazw** [comment]
Hi!still me(^-^)
I found the problem with this result, the code in cp_dataset.py may have some bug:

self.transform = transforms.Compose([transforms.ToTensor(),transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

All the images use this transform method including both rgb image and gray scale image,I guess 
we may need to use different transforms to handle rgb and gray.

**Comment by Amazingren** [comment]
> Hi!still me(^-^)
> I found the problem with this result, the code in cp_dataset.py may have some bug:
> 
> self.transform = transforms.Compose([transforms.ToTensor(),transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])
> 
> All the images use this transform method including both rgb image and gray scale image,I guess
> we may need to use different transforms to handle rgb and gray.

Hi @amandazw,
Yes, you can actually have a try.

**Comment by Amazingren** [comment]
> Hi @Amazingren,
> I'm here to return the result.
> ![000010_0](https://user-images.githubusercontent.com/20120287/120579610-66755b80-c45a-11eb-826c-4156028e57fc.jpg)
> The GMM step is good, but after I finished the TOM step,I run the test of TOM:
> ![000010_0](https://user-images.githubusercontent.com/20120287/120579931-e26fa380-c45a-11eb-8960-223fdde66b3f.jpg)
> I use pytorch 1.1.0, torchvision 0.3.0 to train GMM, using torch 1.8.1+cu111,torchvision 0.9.1+cu111 to train TOM as when I train the TOM model,it showed CUDA out of memory,so I changed to another higher performance GPU.

I highly recommend you conduct all experiments under the same environment(say 0.4.1) first, and all those settings I keep the same as cp-vton-plus, it may matters.
