### ISSUE TITLE
How much GPU memory is needed for TOM stage training?

### ISSUE THREAD

**Issue by GPTAlgoPro** [Amazingren/CIT#4]
python train.py --name TOM --stage TOM --workers 4 --save_count 5000 --shuffle
Namespace(batch_size=4, checkpoint='', checkpoint_dir='/home/admin/workspace/project/CIT/checkpoints', data_list='train_pairs.txt', datamode='train', dataroot='/home/admin/workspace/project/CIT/data', decay_step=100000, display_count=100, fine_height=256, fine_width=192, gpu_ids='0', grid_size=5, keep_step=100000, lr=0.0001, name='TOM', radius=5, save_count=5000, shuffle=True, stage='TOM', tensorboard_dir='/home/admin/workspace/project/CIT/tensorboard', workers=4)
Start to train stage: TOM, named: TOM!

......

RuntimeError: CUDA error: out of memory
terminate called without an active exception
Aborted

**Comment by Amazingren** [comment]
Hi @sunkaianna,

We train TOM on one V100 GPU(32G) with batchsize=8, and it will cost no more than 2 days. you can adjust the batchsize if your GPU memory is lower.
